# Generated by Django 4.2.16 on 2026-03-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0057_teammemberracelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonateRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=120)),
                (
                    "comment",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donate_request",
                        to="website.vtbpayment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
