# Generated by Django 4.2.30 on 2026-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donate", "0002_clubmember_donationperiod_memberdonation"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberdonation",
            name="paid_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата взноса"),
        ),
        migrations.AddField(
            model_name="memberdonation",
            name="recipient",
            field=models.CharField(
                blank=True,
                choices=[("tamila", "Тамиле"), ("sbp", "СБП через сайт")],
                max_length=20,
                verbose_name="Кому",
            ),
        ),
    ]
