version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "kolco24.kolco24.wsgi:application" ]
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - nginx_network
      - kolco24_default
#  runmailer:
#    build: .
#    command: [ "python", "manage.py", "runmailer" ]
#    volumes:
#      - .:/app
#    depends_on:
#      - db
#    networks:
#      - kolco24_default
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kolco24
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kolco24_default

networks:
  kolco24_default:
  nginx_network:
    external: true