version: '3'
services:
  kolco24_web:
    build: .
    container_name: kolco24_django
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8000:8000"
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "kolco24.wsgi:application" ]
    volumes:
      - ./kolco24:/app
    depends_on:
      - kolco24_db
    networks:
      - nginx_network
      - kolco24_default
  kolco24_runmailer:
    build: .
    command: [ "python", "manage.py", "runmailer" ]
    volumes:
      - .:/app
    depends_on:
      - kolco24_web
    networks:
      - kolco24_default
  kolco24_db:
    image: postgres:14
    container_name: kolco24_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kolco24
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - kolco24_db:/var/lib/postgresql/data
    networks:
      - kolco24_default

networks:
  kolco24_default:
  nginx_network:
    external: true

volumes:
  kolco24_db: