[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "kolco24.settings"
python_files = "tests.py test_*.py"

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["src"]
