# Generated by Django 2.0.7 on 2018-10-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_auto_20181010_0115"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="get_map",
            field=models.BooleanField(default=False),
        ),
    ]
