# Generated by Django 2.2.3 on 2019-07-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_auto_20190708_1235"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="PaymentsYa",
        ),
    ]
