# Generated by Django 2.2.3 on 2019-07-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_coupons_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
