# Generated by Django 3.2.15 on 2022-08-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_auto_20210731_1905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlpoint",
            name="year",
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name="team",
            name="year",
            field=models.IntegerField(default=2022),
        ),
    ]
