# Generated by Django 3.2.15 on 2023-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_auto_20221014_0042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlpoint",
            name="year",
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name="takenkp",
            name="year",
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name="team",
            name="year",
            field=models.IntegerField(default=23),
        ),
    ]
