# Generated by Django 3.2.19 on 2023-08-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15, verbose_name="Код")),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.race",
                        verbose_name="Гонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="category2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.category",
                verbose_name="Категория",
            ),
        ),
    ]
