# Generated by Django 3.2.19 on 2023-08-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0026_auto_20230815_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="category",
            name="short_name",
            field=models.CharField(
                default="", max_length=15, verbose_name="Короткое название"
            ),
        ),
    ]
