# Generated by Django 3.2.19 on 2023-08-17 08:15

from django.db import migrations, models

from website.forms import category2_from_dist
from website.models import Team


def pupulate_teams_category2(apps, schema_editor):
    for team in Team.objects.filter(year=2023):
        team.category2 = category2_from_dist(team.dist, team.ucount)
        team.save(update_fields=["category2"])


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0026_auto_20230815_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="category",
            name="short_name",
            field=models.CharField(
                default="", max_length=15, verbose_name="Короткое название"
            ),
        ),
        migrations.RunPython(pupulate_teams_category2),
    ]
