# Generated by Django 3.2.19 on 2023-10-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0030_alter_pointtag_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="takenkp",
            name="nfc",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="takenkp",
            name="phone_uuid",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="takenkp",
            name="timestamp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="takenkp",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
