# Generated by Django 3.2.19 on 2023-10-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0031_takenkp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="takenkp",
            name="timestamp",
            field=models.BigIntegerField(default=0),
        ),
    ]
