# Generated by Django 3.2.25 on 2024-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0036_racelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="dist",
            field=models.CharField(max_length=15),
        ),
    ]
