# Generated by Django 3.2.25 on 2024-09-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0037_alter_team_dist"),
    ]

    operations = [
        migrations.CreateModel(
            name="SbpPaymentRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(max_length=50, verbose_name="Название банка"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Получатель")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Получатель платежа",
                "verbose_name_plural": "Получатели платежей",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="athlet",
        ),
        migrations.AddField(
            model_name="payment",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.sbppaymentrecipient",
            ),
        ),
    ]
