# Generated by Django 4.2.14 on 2024-10-04 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0043_checkpointtag_check_method_checkpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="date_end",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата окончания"
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="is_legend_visible",
            field=models.BooleanField(default=False, verbose_name="Легенда открыта"),
        ),
        migrations.AddField(
            model_name="race",
            name="is_reg_open",
            field=models.BooleanField(
                default=False, verbose_name="Регистрация открыта"
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="is_teams_editable",
            field=models.BooleanField(
                default=False, verbose_name="Команды редактируемы"
            ),
        ),
        migrations.AlterField(
            model_name="checkpointtag",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="website.checkpoint",
                verbose_name="КП",
            ),
        ),
    ]
