# Generated by Django 4.2.14 on 2025-09-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0046_race_is_photo_upload_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название пункта меню"
                    ),
                ),
                (
                    "url",
                    models.CharField(max_length=255, verbose_name="URL пункта меню"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order"],
            },
        ),
    ]
