# Generated by Django 4.2.14 on 2025-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0047_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="header_image",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Картинка в шапке"
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="header_logo",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Логотип в шапке"
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="reg_status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Откроется"),
                    ("open", "Открыта"),
                    ("sold_out", "Мест нет"),
                ],
                db_index=True,
                default="upcoming",
                max_length=16,
                verbose_name="Статус регистрации",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="cost",
            field=models.IntegerField(default=0, verbose_name="Стоимость участия"),
        ),
    ]
