# Generated by Django 4.2.14 on 2025-09-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0047_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
    ]

