# Generated by Django 4.2.16 on 2025-09-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0048_add_reg_status_to_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="VTBPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "order_code",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("amount_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("status_description", models.CharField(blank=True, max_length=128)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("pay_url", models.URLField(blank=True, max_length=500)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="VTBPreparedPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("qrc_id", models.CharField(blank=True, max_length=128)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepared_payments",
                        to="website.vtbpayment",
                    ),
                ),
            ],
        ),
    ]
