# Generated by Django 4.2.16 on 2025-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0049_vtbpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="map",
            field=models.IntegerField(default=0),
        ),
    ]
