# Generated by Django 4.2.16 on 2025-09-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0050_payment_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "people_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество человек"
                    ),
                ),
                (
                    "passenger_contacts",
                    models.JSONField(
                        default=list,
                        help_text="Список участников с их контактами",
                        verbose_name="Участники",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("processed", "Обработана"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на автобус",
                "verbose_name_plural": "Заявки на автобус",
                "ordering": ("-created_at",),
            },
        ),
    ]
