# Generated by Django 4.2.16 on 2025-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0051_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее сканирование",
            ),
        ),
    ]
