# Generated by Django 4.2.16 on 2025-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0052_tag_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
