# Generated by hand for BreakfastRegistration model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0053_team_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakfastRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "people_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество человек"
                    ),
                ),
                (
                    "attendees",
                    models.JSONField(
                        default=list,
                        help_text="Список участников и их предпочтений",
                        verbose_name="Участники",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("processed", "Обработана"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakfast_registrations",
                        to="website.race",
                        verbose_name="Гонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на завтрак",
                "verbose_name_plural": "Заявки на завтрак",
                "ordering": ("-created_at",),
            },
        ),
    ]
