# Generated by Codex CLI for TeamFinishLog model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0055_teamstartlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFinishLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_tag_id",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID тега участника",
                    ),
                ),
                (
                    "tag_uid",
                    models.CharField(blank=True, max_length=64, verbose_name="UID тега"),
                ),
                (
                    "recorded_at",
                    models.BigIntegerField(verbose_name="Время финиша (мс)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_finish_logs",
                        to="website.race",
                        verbose_name="Гонка",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finish_logs",
                        to="website.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Финиш команды",
                "verbose_name_plural": "Финиши команд",
            },
        ),
    ]
