# Generated by Codex CLI for TeamMemberRaceLog model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0056_teamfinishlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMemberRaceLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.BigIntegerField(default=0, verbose_name="Время старта (мс)"),
                ),
                (
                    "finish_time",
                    models.BigIntegerField(default=0, verbose_name="Время финиша (мс)"),
                ),
                (
                    "member_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_logs",
                        to="website.tag",
                        verbose_name="Тег участника",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_race_logs",
                        to="website.race",
                        verbose_name="Гонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат участника",
                "verbose_name_plural": "Результаты участников",
                "unique_together": {("race", "member_tag")},
            },
        ),
    ]
