# Generated by Django 4.2.30 on 2026-05-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0057_teammemberracelog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="time_limit_min",
        ),
    ]
