# Generated by Django 4.2.30 on 2026-05-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0058_remove_race_time_limit_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="slug",
            field=models.SlugField(blank=True, max_length=50, verbose_name="URL-slug"),
        ),
    ]
