# Generated by Django 4.2.30 on 2026-05-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0062_raceadmin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="coupon",
        ),
        migrations.DeleteModel(
            name="Coupons",
        ),
    ]
