# Generated by Django 4.2.30 on 2026-05-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0063_remove_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="agree_news",
            field=models.BooleanField(default=False),
        ),
    ]
