# Generated by Django 4.2.30 on 2026-05-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0065_unique_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FastLogin",
        ),
    ]
