# Generated by Django 4.2.30 on 2026-05-29 21:54

from django.db import migrations, models

# Backfill mapping mirrors the legacy JS `switch` in add_team.html:
#   category ids 8, 16            -> [2, 3]   (min=2, max=3)
#   category ids 9, 13, 17, 21, 24 -> [4, 5, 6] (min=4, max=6)
#   everything else                -> [2]       (min=2, max=2)
# It is a no-op when these ids are absent (fresh / test DB).
TEAM_SIZE_BACKFILL = {
    8: (2, 3),
    16: (2, 3),
    9: (4, 6),
    13: (4, 6),
    17: (4, 6),
    21: (4, 6),
    24: (4, 6),
}
DEFAULT_TEAM_SIZE = (2, 2)


def backfill_team_sizes(apps, schema_editor):
    Category = apps.get_model("website", "Category")
    for category in Category.objects.all():
        min_people, max_people = TEAM_SIZE_BACKFILL.get(category.id, DEFAULT_TEAM_SIZE)
        category.min_people = min_people
        category.max_people = max_people
        category.save(update_fields=["min_people", "max_people"])


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0066_delete_fastlogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="max_people",
            field=models.IntegerField(default=6, verbose_name="Максимум участников"),
        ),
        migrations.AddField(
            model_name="category",
            name="min_people",
            field=models.IntegerField(default=2, verbose_name="Минимум участников"),
        ),
        migrations.RunPython(backfill_team_sizes, migrations.RunPython.noop),
    ]
