# Generated by Django 4.2.30 on 2026-05-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0067_category_max_people_category_min_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="RacePriceTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена за человека")),
                (
                    "active_until",
                    models.DateField(verbose_name="Действует по (включительно)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_tiers",
                        to="website.race",
                        verbose_name="Гонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ценовой период",
                "verbose_name_plural": "Ценовые периоды",
                "ordering": ["active_until", "order"],
            },
        ),
    ]
