# Generated by Django 4.2.30 on 2026-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0069_remove_race_is_reg_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="place",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Место"
            ),
        ),
    ]
