# Generated by Django 4.2.30 on 2026-05-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0070_alter_race_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="people_limit",
            field=models.IntegerField(default=0, verbose_name="Лимит участников"),
        ),
        migrations.AddField(
            model_name="race",
            name="people_limit",
            field=models.IntegerField(default=0, verbose_name="Лимит участников"),
        ),
    ]
