# Generated by Django 4.2.30 on 2026-06-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0071_category_people_limit_race_people_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="vtb_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_payment",
                to="website.vtbpayment",
            ),
        ),
    ]
