# Generated by Django 4.2.30 on 2026-06-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0075_rename_race_is_active_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
