# Generated by Django 4.2.30 on 2026-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0076_athlet_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
