# Generated by Django 4.2.30 on 2026-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0077_checkpoint_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
