# Generated by Django 4.2.30 on 2026-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0078_category_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
