# Generated by Django 4.2.30 on 2026-06-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0079_race_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointtag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
