# Generated by Django 4.2.30 on 2026-06-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0081_rename_tag_id_to_nfc_uid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkpointtag",
            unique_together={("point", "nfc_uid")},
        ),
    ]
