# Generated by Django 4.2.30 on 2026-06-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0082_checkpointtag_unique_point_nfc_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="is_legend_locked",
            field=models.BooleanField(default=False, verbose_name="Легенда заперта"),
        ),
        migrations.AddField(
            model_name="checkpointtag",
            name="bid",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="Идентификатор бандла",
            ),
        ),
        migrations.AddField(
            model_name="checkpointtag",
            name="bundle_blob",
            field=models.JSONField(blank=True, null=True, verbose_name="Бандл"),
        ),
        migrations.AddField(
            model_name="checkpointtag",
            name="code",
            field=models.BinaryField(blank=True, null=True, verbose_name="Код тега"),
        ),
        migrations.AddField(
            model_name="checkpointtag",
            name="unlocks",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocked_by",
                to="website.checkpoint",
                verbose_name="Отпирает КП",
            ),
        ),
        migrations.CreateModel(
            name="CheckpointSecret",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_key", models.BinaryField(verbose_name="Ключ контента")),
                ("enc_blob", models.JSONField(verbose_name="Зашифрованная легенда")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkpoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret",
                        to="website.checkpoint",
                        verbose_name="КП",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секрет КП",
                "verbose_name_plural": "Секреты КП",
            },
        ),
    ]
