# Generated by Django 4.2.30 on 2026-06-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0083_checkpoint_is_legend_locked_checkpointtag_bid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="is_legend_visible",
        ),
    ]
