# Generated by Django 4.2.30 on 2026-06-16 19:53

from django.db import migrations, models


def draft_to_hidden(apps, schema_editor):
    Checkpoint = apps.get_model("website", "Checkpoint")
    Checkpoint.objects.filter(type="draft").update(type="hidden")


def hidden_to_draft(apps, schema_editor):
    Checkpoint = apps.get_model("website", "Checkpoint")
    Checkpoint.objects.filter(type="hidden").update(type="draft")


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0084_remove_race_is_legend_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkpoint",
            name="type",
            field=models.CharField(
                choices=[
                    ("start", "Старт"),
                    ("finish", "Финиш"),
                    ("test", "Тест"),
                    ("kp", "КП"),
                    ("hidden", "Скрытый"),
                ],
                default="kp",
                max_length=50,
                verbose_name="Тип точки",
            ),
        ),
        migrations.RunPython(draft_to_hidden, hidden_to_draft),
    ]
