# Generated by Django 4.2.30 on 2026-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0085_rename_checkpoint_draft_to_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
    ]
