# Generated by Django 4.2.30 on 2026-06-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0086_tag_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpoint",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Без цвета"),
                    ("red", "Красный"),
                    ("blue", "Синий"),
                    ("green", "Зелёный"),
                    ("yellow", "Жёлтый"),
                    ("orange", "Оранжевый"),
                    ("purple", "Фиолетовый"),
                ],
                default="",
                max_length=20,
                verbose_name="Цвет КП",
            ),
        ),
    ]
