# Generated by Django 4.2.30 on 2026-06-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0087_checkpoint_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointtag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provisioned_tags",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем создан",
            ),
        ),
    ]
