# Generated by Django 4.2.30 on 2026-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0088_checkpointtag_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkpointtag",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="checkpointtag",
            name="nfc_uid",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="UID тега"
            ),
        ),
    ]
