# Generated by Django 4.2.30 on 2026-06-20 21:06

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def dedupe_nfc_uids(apps, schema_editor):
    """Resolve duplicate ``nfc_uid`` rows before the global unique index lands.

    The previous ``unique_together("point", "nfc_uid")`` constraint permitted the
    same UID on different checkpoints. The new global ``unique=True`` cannot
    coexist with such duplicates, so the ``AlterField`` below would raise an
    ``IntegrityError`` at deploy time. A chip is physically at exactly one КП, so
    a duplicate is stale data: keep the lowest-id (first-provisioned) row per UID
    and delete the rest, logging what was removed for audit.
    """
    CheckpointTag = apps.get_model("website", "CheckpointTag")
    seen = {}
    for tag in CheckpointTag.objects.order_by("nfc_uid", "id").iterator():
        keep_id = seen.get(tag.nfc_uid)
        if keep_id is None:
            seen[tag.nfc_uid] = tag.id
            continue
        logger.warning(
            "Deleting duplicate CheckpointTag id=%s nfc_uid=%s point=%s "
            "(kept id=%s) to satisfy the new global nfc_uid unique constraint",
            tag.id,
            tag.nfc_uid,
            tag.point_id,
            keep_id,
        )
        tag.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0088_checkpointtag_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkpointtag",
            unique_together=set(),
        ),
        migrations.RunPython(dedupe_nfc_uids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="checkpointtag",
            name="nfc_uid",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="UID тега"
            ),
        ),
    ]
