# Generated by Django 4.2.30 on 2026-06-20 21:06

from django.db import migrations, models


def dedupe_nfc_uids(apps, schema_editor):
    """Detect duplicate ``nfc_uid`` rows before the global unique index lands.

    The previous ``unique_together("point", "nfc_uid")`` constraint permitted the
    same UID on different checkpoints. The new global ``unique=True`` cannot
    coexist with such duplicates, so the ``AlterField`` below would raise an
    ``IntegrityError`` at deploy time.

    Abort with a clear error so a human resolves duplicates manually — consistent
    with migration 0081's collision-handling approach. Silent auto-deletion is
    unsafe: the higher-id row may be the *current* binding (a chip re-provisioned
    to a different КП after initial provisioning), and deleting it destroys crypto
    and M2M data that cannot be recovered from logs.
    """
    CheckpointTag = apps.get_model("website", "CheckpointTag")
    seen = {}
    duplicates = []
    for tag in CheckpointTag.objects.order_by("nfc_uid", "id").iterator():
        if tag.nfc_uid in seen:
            duplicates.append((seen[tag.nfc_uid], tag.id, tag.nfc_uid, tag.point_id))
        else:
            seen[tag.nfc_uid] = tag.id
    if duplicates:
        details = ", ".join(
            f"rows {a} and {b} share nfc_uid='{u}' (point_ids: see DB)"
            for a, b, u, _p in duplicates
        )
        raise RuntimeError(
            "Cannot add global nfc_uid unique constraint: duplicate CheckpointTag "
            f"rows exist ({details}). Resolve these duplicates manually before "
            "migrating — determine which row is the current chip binding and delete "
            "the stale one."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0088_checkpointtag_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checkpointtag",
            unique_together=set(),
        ),
        migrations.RunPython(dedupe_nfc_uids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="checkpointtag",
            name="nfc_uid",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="UID тега"
            ),
        ),
    ]
