# Generated by Django 4.2.30 on 2026-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0090_rename_checkpointtag_point_checkpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="control_time",
            field=models.IntegerField(
                default=0, verbose_name="Контрольное время (мин)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="overtime_penalty",
            field=models.IntegerField(
                default=0, verbose_name="Штраф за минуту просрочки (баллы)"
            ),
        ),
    ]
