# Generated by Django 4.2.30 on 2026-09-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_app", "0005_racepromo"),
        ("website", "0092_newspost_publication_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="promo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="race_app.racepromo",
            ),
        ),
    ]
