# Generated by Django 4.2.30 on 2026-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0093_payment_discount_amount_payment_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="submit_token",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submit_token", ""), _negated=True),
                fields=("owner", "submit_token"),
                name="team_owner_submit_token_uniq",
            ),
        ),
    ]
