# Generated by Django 4.2.30 on 2026-09-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0094_team_submit_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vtb_refund_id", models.CharField(max_length=64, unique=True)),
                ("amount", models.FloatField(default=0)),
                ("people", models.FloatField(default=0)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="website.payment",
                    ),
                ),
            ],
            options={
                "ordering": ("-refunded_at", "-id"),
            },
        ),
    ]
