# Generated by Django 4.2.30 on 2026-09-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0096_backfill_legacy_refunds"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="code",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="Код браслета"
            ),
        ),
    ]
