# Generated by Django 4.2.30 on 2026-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0098_alter_checkpointtag_check_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="map_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Оффлайн-карта (MBTiles)",
            ),
        ),
    ]
