# Generated by Django 4.2.16 on 2026-03-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramChat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(unique=True, verbose_name="ID чата в Telegram"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("chat_type", models.CharField(max_length=50, verbose_name="Тип чата")),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        help_text="Исходный JSON-файл, из которого загружен чат.",
                        max_length=255,
                        verbose_name="Файл экспорта",
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырые данные чата"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram чат",
                "verbose_name_plural": "Telegram чаты",
                "ordering": ("name", "telegram_id"),
            },
        ),
        migrations.CreateModel(
            name="TelegramMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(verbose_name="ID сообщения в Telegram"),
                ),
                ("message_type", models.CharField(max_length=32, verbose_name="Тип сообщения")),
                ("sent_at", models.DateTimeField(verbose_name="Дата сообщения")),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата редактирования"
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отправитель"
                    ),
                ),
                (
                    "sender_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID отправителя"
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Исполнитель сервисного действия",
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID исполнителя сервисного действия",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Сервисное действие"
                    ),
                ),
                (
                    "inviter",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Кто пригласил"
                    ),
                ),
                (
                    "reply_to_message_id",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID сообщения, на которое это ответ",
                    ),
                ),
                (
                    "forwarded_from",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Источник пересланного сообщения",
                    ),
                ),
                (
                    "forwarded_from_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID источника пересланного сообщения",
                    ),
                ),
                (
                    "via_bot",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Бот-источник"
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст сообщения")),
                (
                    "raw_text",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Исходное поле text"
                    ),
                ),
                (
                    "text_entities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Разметка текста"
                    ),
                ),
                (
                    "reactions",
                    models.JSONField(blank=True, default=list, verbose_name="Реакции"),
                ),
                (
                    "media_type",
                    models.CharField(blank=True, max_length=64, verbose_name="Тип медиа"),
                ),
                ("photo", models.CharField(blank=True, max_length=255, verbose_name="Фото")),
                ("file", models.CharField(blank=True, max_length=255, verbose_name="Файл")),
                (
                    "file_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, max_length=255, verbose_name="MIME-тип"),
                ),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Миниатюра"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Заголовок"),
                ),
                (
                    "performer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Исполнитель"
                    ),
                ),
                (
                    "sticker_emoji",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Emoji стикера"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длительность, сек."
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высота"
                    ),
                ),
                (
                    "photo_file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер фото, байт"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер файла, байт"
                    ),
                ),
                (
                    "thumbnail_file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Размер миниатюры, байт"
                    ),
                ),
                (
                    "live_location_period_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Период live location, сек.",
                    ),
                ),
                (
                    "media_spoiler",
                    models.BooleanField(
                        default=False, verbose_name="Медиа под спойлером"
                    ),
                ),
                (
                    "members",
                    models.JSONField(blank=True, default=list, verbose_name="Участники"),
                ),
                ("poll", models.JSONField(blank=True, null=True, verbose_name="Опрос")),
                (
                    "inline_bot_buttons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Inline кнопки бота"
                    ),
                ),
                (
                    "location_information",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Информация о локации",
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырые данные сообщения"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="challenge.telegramchat",
                        verbose_name="Чат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram сообщение",
                "verbose_name_plural": "Telegram сообщения",
                "ordering": ("sent_at", "telegram_id"),
                "indexes": [
                    models.Index(
                        fields=["chat", "sent_at"], name="challenge_msg_chat_sent_idx"
                    ),
                    models.Index(
                        fields=["message_type"], name="challenge_msg_type_idx"
                    ),
                    models.Index(fields=["sender_id"], name="challenge_msg_sender_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="telegrammessage",
            constraint=models.UniqueConstraint(
                fields=("chat", "telegram_id"),
                name="challenge_chat_message_unique",
            ),
        ),
    ]
