# Generated by Django 4.2.16 on 2026-03-28 23:28

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenge", "0002_challenge_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeMessageBatchReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_day", models.DateField(verbose_name="День сообщений")),
                (
                    "resolution",
                    models.CharField(
                        choices=[("labeled", "Есть тренировки"), ("flood", "Флуд")],
                        max_length=16,
                        verbose_name="Результат разбора",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Когда разобрали",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_batch_reviews",
                        to="challenge.challenge",
                        verbose_name="Челлендж",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_batch_reviews",
                        to="challenge.challengeparticipant",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_message_batch_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто разобрал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разбор пачки сообщений",
                "verbose_name_plural": "Разборы пачек сообщений",
                "ordering": ("message_day", "id"),
            },
        ),
        migrations.CreateModel(
            name="ChallengeTrainingLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("training_date", models.DateField(verbose_name="Дата тренировки")),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("counted", "Засчитана"),
                            ("not_counted", "Не засчитана"),
                        ],
                        max_length=32,
                        verbose_name="Решение",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("run_5_10", "Бег 5-10 км"),
                            ("run_10_plus", "Бег 10+ км"),
                            ("ski_6_12", "Лыжи 6-12 км"),
                            ("ski_12_plus", "Лыжи 12+ км"),
                            ("bike_20_40", "Велосипед 20-40 км"),
                            ("bike_40_plus", "Велосипед 40+ км"),
                            ("swim_1_2", "Плавание 1-2 км"),
                            ("swim_2_plus", "Плавание 2+ км"),
                            ("hike_day", "Поход"),
                            ("gsh_day", "Тренировочный выезд ГШ"),
                        ],
                        max_length=32,
                        verbose_name="Тип тренировки",
                    ),
                ),
                (
                    "base_points",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Базовые баллы"
                    ),
                ),
                (
                    "streak_bonus_points",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Бонус за серию"
                    ),
                ),
                (
                    "total_points",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Итого баллов"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Когда разметили",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_labels",
                        to="challenge.challenge",
                        verbose_name="Челлендж",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_labels",
                        to="challenge.challengeparticipant",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_training_labels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто разметил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размеченная тренировка",
                "verbose_name_plural": "Размеченные тренировки",
                "ordering": ("training_date", "id"),
            },
        ),
        migrations.CreateModel(
            name="ChallengeTrainingLabelMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_links",
                        to="challenge.challengetraininglabel",
                        verbose_name="Разметка тренировки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_label_links",
                        to="challenge.telegrammessage",
                        verbose_name="Сообщение Telegram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь тренировки с сообщением",
                "verbose_name_plural": "Связи тренировок с сообщениями",
            },
        ),
        migrations.DeleteModel(
            name="ChallengeActivity",
        ),
        migrations.AddField(
            model_name="challengetraininglabel",
            name="source_messages",
            field=models.ManyToManyField(
                related_name="training_labels",
                through="challenge.ChallengeTrainingLabelMessage",
                to="challenge.telegrammessage",
                verbose_name="Сообщения-источники",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengetraininglabelmessage",
            constraint=models.UniqueConstraint(
                fields=("label", "message"),
                name="challenge_training_label_message_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="challengetraininglabel",
            index=models.Index(
                fields=["challenge", "participant", "training_date"],
                name="chall_lbl_score_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="challengetraininglabel",
            index=models.Index(
                fields=["challenge", "decision"], name="chall_lbl_dec_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengetraininglabel",
            constraint=models.UniqueConstraint(
                fields=("challenge", "participant", "training_date"),
                name="challenge_training_label_unique_day",
            ),
        ),
        migrations.AddIndex(
            model_name="challengemessagebatchreview",
            index=models.Index(
                fields=["challenge", "participant", "message_day"],
                name="chall_batch_rev_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengemessagebatchreview",
            constraint=models.UniqueConstraint(
                fields=("challenge", "participant", "message_day"),
                name="challenge_message_batch_review_unique_day",
            ),
        ),
    ]
