# Generated by Django 4.2.30 on 2026-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="emailverification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("consumed_at__isnull", True)),
                fields=("email", "purpose"),
                name="unique_active_email_verification",
            ),
        ),
    ]
