# Generated by Django 4.2.30 on 2026-06-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppInstall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "install_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("platform", models.CharField(blank=True, max_length=16)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
