# Generated by Django 4.2.30 on 2026-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appinstall",
            name="install_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
