# Generated by Django 4.2.30 on 2026-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0002_drop_install_id_db_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="appinstall",
            name="key_id",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
