# Generated by Django 4.2.30 on 2026-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0003_appinstall_key_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppAuthFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("key_id", models.CharField(blank=True, max_length=32)),
                ("reason", models.CharField(max_length=32)),
                ("count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("last_path", models.CharField(blank=True, max_length=255)),
                ("last_install_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "unique_together": {("ip", "key_id", "reason")},
            },
        ),
    ]
