# Generated by Django 4.2.30 on 2026-06-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0090_rename_checkpointtag_point_checkpoint"),
        ("mobile", "0006_mobiletoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackPoint",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("install_id", models.CharField(max_length=64)),
                ("segment_id", models.CharField(max_length=64)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("altitude", models.FloatField(null=True)),
                ("vertical_accuracy", models.FloatField(null=True)),
                ("gps_time_ms", models.BigIntegerField()),
                ("trusted_ms", models.BigIntegerField(null=True)),
                ("elapsed_at", models.BigIntegerField()),
                ("boot_count", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_points",
                        to="website.race",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_points",
                        to="website.team",
                    ),
                ),
            ],
        ),
    ]
