# Generated by Django 4.2.30 on 2026-06-29 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0090_rename_checkpointtag_point_checkpoint"),
        ("mobile", "0007_trackpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("source_install_id", models.CharField(max_length=64)),
                ("checkpoint_id", models.IntegerField()),
                ("method", models.CharField(max_length=16)),
                ("cp_code", models.CharField(blank=True, max_length=64)),
                ("cp_nfc_uid", models.CharField(blank=True, max_length=255)),
                ("expected_count", models.IntegerField()),
                ("complete", models.BooleanField()),
                ("verified", models.BooleanField()),
                ("trusted_ms", models.BigIntegerField(null=True)),
                ("wall_ms", models.BigIntegerField()),
                ("elapsed_at", models.BigIntegerField(null=True)),
                ("boot_count", models.IntegerField(null=True)),
                ("loc_lat", models.FloatField(null=True)),
                ("loc_lon", models.FloatField(null=True)),
                ("loc_accuracy", models.FloatField(null=True)),
                ("loc_altitude", models.FloatField(null=True)),
                ("loc_vertical_accuracy", models.FloatField(null=True)),
                ("loc_gps_time_ms", models.BigIntegerField(null=True)),
                ("loc_elapsed_at", models.BigIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="website.race",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="website.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkPresent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nfc_uid", models.CharField(max_length=255, null=True)),
                ("code", models.CharField(max_length=64, null=True)),
                ("number", models.IntegerField()),
                ("number_in_team", models.IntegerField()),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="present",
                        to="mobile.mark",
                    ),
                ),
            ],
            options={
                "unique_together": {("mark", "number_in_team")},
            },
        ),
    ]
