# Generated by Django 4.2.30 on 2026-07-01 11:01

import django.db.models.deletion
from django.db import migrations, models

import apps.mobile.models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0008_mark_markpresent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_id", models.CharField(max_length=64)),
                (
                    "image",
                    models.FileField(upload_to=apps.mobile.models._mark_photo_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="mobile.mark",
                    ),
                ),
            ],
            options={
                "unique_together": {("mark", "frame_id")},
            },
        ),
    ]
