# Generated by Django 4.2.30 on 2026-07-01 11:54

from django.db import migrations, models

import apps.mobile.models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0009_markphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markphoto",
            name="image",
            field=models.FileField(
                max_length=255, upload_to=apps.mobile.models._mark_photo_path
            ),
        ),
    ]
