# Generated by Django 4.2.30 on 2026-07-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0091_category_control_time_category_overtime_penalty"),
        ("mobile", "0010_alter_markphoto_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeScan",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("source_install_id", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=16)),
                ("participant_number", models.IntegerField()),
                ("nfc_uid", models.CharField(max_length=255)),
                ("wall_ms", models.BigIntegerField()),
                ("trusted_ms", models.BigIntegerField(null=True)),
                ("elapsed_at", models.BigIntegerField(null=True)),
                ("boot_count", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_scans",
                        to="website.race",
                    ),
                ),
            ],
        ),
    ]
