# Generated by Django 4.2.30 on 2026-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0011_judgescan"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="trackpoint",
            index=models.Index(
                fields=["race", "team", "-gps_time_ms"], name="mobile_tp_race_team_ts"
            ),
        ),
    ]
