from .views_ import (
    AddNewsPostView,
    AddTeam,
    AllTeamsResultView,
    RaceIdRedirectView,
    TeamMemberRaceLogView,
    TeamPointsView,
    contacts,
    edit_page,
    page,
    privacy_policy,
    refund_policy,
    regulations,
    rules,
    service_order_rules,
    upload_photo,
)
