# Generated by Django 2.0.7 on 2018-07-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YandexPayment',
            new_name='Payments',
        ),
    ]
