# Generated by Django 2.0.7 on 2018-10-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_fastlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=50)),
                ('get_package', models.BooleanField(default=False)),
                ('get_number', models.BooleanField(default=False)),
                ('give_paper', models.BooleanField(default=False)),
                ('give_photos', models.BooleanField(default=False)),
                ('category', models.CharField(default='', max_length=50)),
                ('start_number', models.CharField(default='', max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('distance_time', models.DurationField(blank=True, null=True)),
                ('penalty', models.IntegerField(default=0)),
                ('dnf', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='distance_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='get_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='get_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='give_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='give_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='start_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
