# Generated by Django 2.0.7 on 2018-10-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_team_get_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamadminlog",
            name="get_map",
            field=models.BooleanField(default=False),
        ),
    ]
