# Generated by Django 2.2.6 on 2019-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_controlpoints_takenkp'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='iterator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controlpoint',
            name='cost',
            field=models.IntegerField(default=1),
        ),
    ]
