# Generated by Django 2.2.15 on 2020-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_auto_20200902_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsya",
            name="sha1_hash",
            field=models.CharField(max_length=50),
        ),
    ]
