# Generated by Django 3.2.19 on 2023-08-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="map_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="map_count_paid",
            field=models.IntegerField(default=0),
        ),
    ]
