# Generated by Django 3.2.19 on 2023-08-26 08:27

from django.db import migrations, models


def set_order(apps, schema_editor):
    Payment = apps.get_model("website", "Payment")
    for payment in Payment.objects.all():
        payment.order = payment.id
        payment.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_short_name_in_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("done", "Оплачено"),
                    ("draft_with_info", "Черновик с информацией"),
                    ("cancel", "Отменено"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.RunPython(set_order),
    ]
