# Generated by Django 3.2.25 on 2024-09-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='place',
            field=models.CharField(default='', max_length=50, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='takenkp',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
