# Generated by Django 3.2.25 on 2024-09-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0035_newspost"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceLink",
            options={"verbose_name": "Ссылка", "verbose_name_plural": "Ссылки"},
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("url", models.CharField(max_length=255, verbose_name="Ссылка")),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="website.race",
                        verbose_name="Гонка",
                    ),
                ),
            ],
        ),
    ]
