# Generated by Django 3.2.25 on 2024-09-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0038_add_payment_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlpoint",
            options={
                "ordering": ["id"],
                "verbose_name": "Контрольная точка",
                "verbose_name_plural": "Контрольные точки",
            },
        ),
        migrations.AddField(
            model_name="controlpoint",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.race",
                verbose_name="Гонка",
            ),
        ),
        migrations.AlterField(
            model_name="controlpoint",
            name="cost",
            field=models.IntegerField(default=1, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="controlpoint",
            name="year",
            field=models.IntegerField(default=2024, verbose_name="Год"),
        ),
    ]
