# Generated by Django 4.2.30 on 2026-06-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website", "0072_payment_vtb_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceExtra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("free_per_team", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="website.race",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("race", "code")},
            },
        ),
        migrations.CreateModel(
            name="PaymentExtra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("unit_price", models.IntegerField(default=0)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="website.payment",
                    ),
                ),
                (
                    "race_extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_extras",
                        to="race_app.raceextra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamExtra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("count_paid", models.IntegerField(default=0)),
                (
                    "race_extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_extras",
                        to="race_app.raceextra",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras",
                        to="website.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "race_extra")},
            },
        ),
    ]
