# Generated by Django 4.2.30 on 2026-07-02 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0091_category_control_time_category_overtime_penalty"),
        ("race_app", "0002_migrate_maps_to_extras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("final", "final")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="website.race",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.IntegerField(default=0)),
                ("team_id", models.IntegerField()),
                (
                    "start_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("team_name", models.CharField(blank=True, default="", max_length=200)),
                ("members", models.TextField(blank=True, default="")),
                ("club", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(blank=True, default="", max_length=200)),
                ("member_count", models.IntegerField(default=0)),
                ("category_id", models.IntegerField()),
                (
                    "category_code",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "category_short_name",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("nfc_checkpoints", models.TextField(blank=True, default="")),
                ("nfc_count", models.IntegerField(default=0)),
                ("nfc_score", models.IntegerField(default=0)),
                ("photo_checkpoints", models.TextField(blank=True, default="")),
                ("photo_count", models.IntegerField(default=0)),
                ("photo_score", models.IntegerField(default=0)),
                ("chips_count", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("start_time_ms", models.BigIntegerField(default=0)),
                ("finish_time_ms", models.BigIntegerField(default=0)),
                ("duration_ms", models.BigIntegerField(default=0)),
                (
                    "duration_str",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("penalty", models.IntegerField(default=0)),
                ("final_score", models.IntegerField(default=0)),
                ("dnf", models.BooleanField(default=False)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="race_app.protocol",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["protocol", "category_id"],
                        name="race_app_pr_protoco_512545_idx",
                    )
                ],
            },
        ),
    ]
