# Generated by Django 4.2.30 on 2026-07-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_app", "0003_protocol_protocolrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
