# Generated by Django 4.2.30 on 2026-09-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0092_newspost_publication_fields"),
        ("race_app", "0004_protocol_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RacePromo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        default="percent",
                        max_length=8,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("max_uses", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promos",
                        to="website.race",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("race", "code")},
            },
        ),
    ]
